name: Migrate Database (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to migrate (production/staging)'
        required: true
        default: 'production'

jobs:
  migrate:
    name: Run Supabase Migrations
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run database migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          supabase db push --db-url "$DATABASE_URL"

